### ISSUE TITLE
tipo_runner produces nondeterministic outputs, while running GGUF model directly doesn't

### ISSUE THREAD

**Issue by asagi4** [KohakuBlueleaf/KGen#8]
Hello again,

I have  a reproducing testcase for showing that the kgen module produces non-repeatable outputs:

```
import transformers
from llama_cpp import Llama
import kgen.models
from kgen.executor.tipo import apply_tipo_prompt, tipo_runner
from pathlib import Path


p = {
    'meta': {'meta': '', 'rating': None, 'artist': None, 'characters': None, 'copyrights': None, 'quality': '', 'aspect_ratio': '1.0'},
    'general': 'test',
    'nl_prompt': '',
    'mode': None,
    'length': 'short',
    'expand': True,
    'gen_meta': False,
}

prompt = apply_tipo_prompt(**p)
# Taken from a TIPO output
longprompt ="""
prompt aspect_ratio: 1.0
target: <|very_short|> <|tag_to_long|>
tag: yellow eyes, looking at viewer, no humans, blush stickers, open mouth, full body, white background, standing, standing on one leg, test tube, simple background, pokemon (creature), clothed pokemon, holding, holding test tube, solo, smile, :d
"""

def testcase():
    NUM_ITERS = 3
    kwargs = dict(
        temperature=0.35,
        min_p=0.1,
        top_p=0.95,
        top_k=60,
        seed=42,
    )
    model_name = 'KBlueLeaf/TIPO-200M-ft'
    filename = "TIPO-200M-ft-F16.gguf"
    device = 'cuda'
    model_path = Path(transformers.file_utils.get_file_from_repo("KBlueLeaf/TIPO-200M-ft", filename=filename))
    model = Llama(str(model_path), n_ctx=1024, n_gpu_layers=0 if device == 'cpu' else 1000, verbose=False)

    # I tried to make these as close as possible to what the kgen module does
    raw_results = [model.create_completion(prompt, max_tokens=512, repeat_penalty=1.17, **kwargs)['choices'][0]['text'] for _ in range(NUM_ITERS)]
    assert all(x == raw_results[0] for x in raw_results)
    raw_results2 = [model.create_completion(longprompt, max_tokens=512, repeat_penalty=1.17, **kwargs)['choices'][0]['text'] for _ in range(NUM_ITERS)]
    assert all(x == raw_results2[0] for x in raw_results2)


    kgen.models.model_dir = model_path.parent
    kgen.models.load_model(model_path, gguf=True, device=device)
    operations = [[None, 'short', True], ['tag_to_long', 'very_short', False]]
    kgen_results = [[x for x in tipo_runner(p['meta'], operations, p['general'], p['nl_prompt'], p['gen_meta'], **kwargs)] for _ in range(NUM_ITERS)]
    print("kgen results", [x[0]['general'] for x in kgen_results])
    assert all(x[0]['general'] == kgen_results[0][0]['general'] for x in kgen_results)


if __name__ == "__main__":
    testcase()
```

Running this code, on my host  I get an assertionerror showing that kgen produces nondeterministic output. I can increase the number of iterations and everything stays deterministic when running the raw Llama model.

In `tipo_runner_generator`, the seed is removed from kwargs on the first iteration through operations, and after that it's None.
However, fixing that still does not make things deterministic; there's also something else that's causing randomness.

I have llama_cpp_python installed from here: https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.4-cu124/llama_cpp_python-0.3.4-cp311-cp311-linux_x86_64.whl

**Comment by asagi4** [comment]
I also tested that running kgen first does not change things

**Comment by KohakuBlueleaf** [comment]
device="cuda" SHOULD have non-deterministic issue that is expected and we don't think it is necessary to keep the reproducibility
If you are using ComfyUI as your inference UI, I will recommend you to use some show-text node to help you to store the prompts.

**Comment by asagi4** [comment]
@KohakuBlueleaf This nondeterminism happens on CPU too! 

My python code shows that it isn't a problem with llama-cpp-python because directly calling the model even on GPU produces deterministic outputs.

Besides the obvious bug with the seed getting set to None if there's more than one operation, the code is doing something that triggers nondeterminism.

**Comment by KohakuBlueleaf** [comment]
First of all the tipo gen is not single pass and it have very complex operation.
You can say something is wrong within the process but plz don't just report something already been wrll known.

Second, i don't want to spend anytime on this thing since as I said, nondeterministic is not a problem in my view.

Third, if you think this is bug and want to fix it you can just open PR.

**Comment by KohakuBlueleaf** [comment]
BTW in my opinion you just need to put a random.seed() before all the tipo_runner.

The seed in kwargs only affects llama.cpp or transformers backbone

**Comment by asagi4** [comment]
@KohakuBlueleaf setting random.seed() does nothing, and as I said, this is not the same problem that you warn about because it happens on CPU too, not just CUDA.

But if you're not interested in fixing it, I suppose there's nothing I can do about that.

**Comment by KohakuBlueleaf** [comment]
You can try pytorch_lightning's seed_everything and if this doesn't work than nothing can work and it is not related to me.

**Comment by KohakuBlueleaf** [comment]
Again, don't just report things which are already well-known.
Give insights.

I'm not your employee, ok?

**Comment by KohakuBlueleaf** [comment]
Fixed in 0.1.7。

**Comment by asagi4** [comment]
@KohakuBlueleaf I'm confused. I *wasn't* reporting a well-known problem because the one you document is specifically about CUDA (unless you don't care at all that your code just seems to give random results all the time for some reason), and I gave you Python code to reproduce the problem I'm seeing and I pointed you at a specific point in the code where you have a bug and even did testing to find out that fixing it isn't enough to fix the issue.

I can't force you to care about any of this, but what kind of bug reports are you looking for if mine falls short of your standards?

**Comment by KohakuBlueleaf** [comment]
> @KohakuBlueleaf I'm confused. I _wasn't_ reporting a well-known problem because the one you document is specifically about CUDA (unless you don't care at all that your code just seems to give random results all the time for some reason), and I gave you Python code to reproduce the problem I'm seeing and I pointed you at a specific point in the code where you have a bug and even did testing to find out that fixing it isn't enough to fix the issue.
> 
> I can't force you to care about any of this, but what kind of bug reports are you looking for if mine falls short of your standards?

You never pointed ANY point where it have bug, all your test code says is "tipo_runner with gguf is nondeterministic" which is indeed well known.
I still need to go through all the runner code to see where is the problem.

All of us knows when use tiporunner with gguf it will be nondeterministic, so it is well-known.

And your test also says NOTHING about the cause at all. You can put tiporunner first than your standalone test behind it and you will find your standalone test become "Nondeterministic" as well.

My standard is simple "be helpful." In your report you are just keep repeating "it happens", but not "why it happens" did you actually think your report provided any clue at all??? Your report helps NOTHING and only be annoying and wastes my time.

**Comment by KohakuBlueleaf** [comment]
Also you should test if my fix do fix things instead arguing with me.
Looks like prove you are helpful in this thread is more important than fixing real problems.

**Comment by asagi4** [comment]
@KohakuBlueleaf I guess you can't read

> In tipo_runner_generator, the seed is removed from kwargs on the first iteration through operations, and after that it's None.
However, fixing that still does not make things deterministic; there's also something else that's causing randomness.

Do you expect me to fix your bug before reporting it? I reported it because I don't know the full fix.

**Comment by KohakuBlueleaf** [comment]
You don't need to do anything before reporting any issue.
But if you think there are anything needs more operations after I close the issue, you should do it by yourself.

I don't care what issue you submit but your later responses to this thread just annoying.

**Comment by KohakuBlueleaf** [comment]
If you think the problem still not resolved 
Open another issue
This thread is off topic and unnecessary
